"""added relationship between tests and tutoringtutoring_sessions

Revision ID: 1fd49ef85909
Revises: efc91ce2ce73
Create Date: 2025-08-15 23:05:21.214890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd49ef85909'
down_revision: Union[str, Sequence[str], None] = 'efc91ce2ce73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutoring_sessions', sa.Column('student_id', sa.Integer(), nullable=False))
    op.add_column('tutoring_sessions', sa.Column('tutor_id', sa.Integer(), nullable=False))
    op.add_column('tutoring_sessions', sa.Column('test_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tutoring_sessions', 'tests', ['test_id'], ['id'])
    op.create_foreign_key(None, 'tutoring_sessions', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'tutoring_sessions', 'tutors', ['tutor_id'], ['id'])
    op.add_column('students', sa.Column('tutor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'tutors', ['tutor_id'], ['id'])
    op.add_column('tests', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tests', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'student_id')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'tutor_id')
    op.drop_constraint(None, 'tutoring_sessions', type_='foreignkey')
    op.drop_constraint(None, 'tutoring_sessions', type_='foreignkey')
    op.drop_constraint(None, 'tutoring_sessions', type_='foreignkey')
    op.drop_column('tutoring_sessions', 'test_id')
    op.drop_column('tutoring_sessions', 'tutor_id')
    op.drop_column('tutoring_sessions', 'student_id')
    # ### end Alembic commands ###
