"""attempting to fix relationships in user JTI for mutliple update statement

Revision ID: 3bc70ea1d300
Revises: cd2b854c6be9
Create Date: 2025-06-23 14:55:59.740493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bc70ea1d300'
down_revision: Union[str, Sequence[str], None] = 'cd2b854c6be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_completed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('session_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fk_students', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fk_students'], ['students.id'], name=op.f('sessions_table_fk_students_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_table_pkey'))
    )
    # ### end Alembic commands ###
