"""added total_score for tests

Revision ID: 4803d2f88b25
Revises: 5a1c942414e6
Create Date: 2025-09-26 22:18:52.301657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4803d2f88b25'
down_revision: Union[str, Sequence[str], None] = '5a1c942414e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('students_id_fkey'), 'students', type_='foreignkey')
    op.drop_constraint(op.f('students_tutor_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'students', 'tutors', ['tutor_id'], ['id'])
    op.add_column('tests', sa.Column('total_score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'total_score')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_tutor_id_fkey'), 'students', 'tutors', ['tutor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('students_id_fkey'), 'students', 'users', ['id'], ['id'])
    # ### end Alembic commands ###
