"""added appropriate relationships to model vars

Revision ID: 767960e0d18d
Revises: 81db3a7610d9
Create Date: 2025-07-30 22:08:19.482026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767960e0d18d'
down_revision: Union[str, Sequence[str], None] = '81db3a7610d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_fk_students_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_fk_tests_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_fk_tutors_fkey'), 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'fk_tutors')
    op.drop_column('sessions', 'fk_tests')
    op.drop_column('sessions', 'fk_students')
    op.drop_column('students', 'tutor_id')
    op.drop_column('tests', 'fk_students')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('fk_students', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('tutor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('fk_students', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('fk_tests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('fk_tutors', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sessions_fk_tutors_fkey'), 'sessions', 'tutors', ['fk_tutors'], ['id'])
    op.create_foreign_key(op.f('sessions_fk_tests_fkey'), 'sessions', 'tests', ['fk_tests'], ['id'])
    op.create_foreign_key(op.f('sessions_fk_students_fkey'), 'sessions', 'students', ['fk_students'], ['id'])
    # ### end Alembic commands ###
