"""centralized test_notes inheritance

Revision ID: 81db3a7610d9
Revises: 9c0465fbd1aa
Create Date: 2025-06-29 15:09:59.190532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81db3a7610d9'
down_revision: Union[str, Sequence[str], None] = '9c0465fbd1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('test_notes', sa.String(), nullable=False))
    op.add_column('tests', sa.Column('fk_students', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tests', 'students', ['fk_students'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'fk_students')
    op.drop_column('tests', 'test_notes')
    # ### end Alembic commands ###
