"""added on delete cascade for students and tutors tables

Revision ID: ed6b867c7651
Revises: 3bc70ea1d300
Create Date: 2025-06-23 16:40:05.476235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6b867c7651'
down_revision: Union[str, Sequence[str], None] = '3bc70ea1d300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('students_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tutors_id_fkey'), 'tutors', type_='foreignkey')
    op.create_foreign_key(None, 'tutors', 'users', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tutors', type_='foreignkey')
    op.create_foreign_key(op.f('tutors_id_fkey'), 'tutors', 'users', ['id'], ['id'])
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_id_fkey'), 'students', 'users', ['id'], ['id'])
    # ### end Alembic commands ###
