"""initial... now that I understand alembic

Revision ID: efc91ce2ce73
Revises: 
Create Date: 2025-07-30 23:06:46.533467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc91ce2ce73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutoring_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('date_completed', sa.TIMESTAMP(), nullable=True),
    sa.Column('payment_amount', sa.Integer(), nullable=True),
    sa.Column('session_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_completed', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=False),
    sa.Column('test_notes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ACTs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_score', sa.Integer(), nullable=False),
    sa.Column('math_score', sa.Integer(), nullable=False),
    sa.Column('reading_score', sa.Integer(), nullable=False),
    sa.Column('science_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PSATs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_score', sa.Integer(), nullable=False),
    sa.Column('math_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SATs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_score', sa.Integer(), nullable=False),
    sa.Column('math_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutors')
    op.drop_table('students')
    op.drop_table('SATs')
    op.drop_table('PSATs')
    op.drop_table('ACTs')
    op.drop_table('users')
    op.drop_table('tests')
    op.drop_table('tutoring_sessions')
    # ### end Alembic commands ###
